<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.shop</groupId>
        <artifactId>shop-base</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>com.shop</groupId>
    <artifactId>shop-admin</artifactId>
    <description>后台管理模块</description>


    <dependencies>
        <dependency>
            <groupId>com.shop</groupId>
            <artifactId>shop-commom</artifactId>
            <version>${package.version}</version>
        </dependency>
        <!-- 文件上传  -->
        <dependency>
            <groupId>com.shop</groupId>
            <artifactId>shop-file</artifactId>
            <version>${package.version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- 文件上传  -->
        <dependency>
            <groupId>com.shop</groupId>
            <artifactId>shop-api</artifactId>
            <version>${package.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.14.3</version> <!-- or latest version -->
        </dependency>

        <!--Markdown 转 Html-->
        <dependency>
            <groupId>com.vladsch.flexmark</groupId>
            <artifactId>flexmark-all</artifactId>
            <version>0.62.2</version>
        </dependency>


        <!-- 只保留 Spring Boot 测试 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <!-- 排除老旧的JUnit4，只保留JUnit5（Jupiter） -->
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.github.lianjiatech</groupId>
            <artifactId>retrofit-spring-boot-starter</artifactId>
            <!-- 请注意版本选择：Spring Boot 2.x 使用 2.x 版本；Spring Boot 3.x / 4.x 使用 4.x 版本 -->
            <version>4.0.2</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <classifier>exec</classifier>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
